In [1]:
import torch
import torch.optim as optim
# 다양한 최적화 알고리즘 구현해 놓은 패키지

In [2]:
torch.manual_seed(1)
# seed 함수 호출해 고정
# seed 고정해 놓으면 매번 랜덤함수 호출 시 동일한 값 호출

#Data

In [4]:
# (x1, y1)=(1, 1), (x2, y2)=(2, 2), (x3, y3)=(3, 3)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [6]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


# Weight Initialization

In [11]:
W = torch.zeros(1, requires_grad=True)  # 학습용 변수 선언
print(W)

tensor([0.], requires_grad=True)


In [12]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


# Hypothesis

In [13]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


# Cost

In [14]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [15]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [16]:
print(hypothesis - y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [17]:
print((hypothesis - y_train) ** 2)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)


In [18]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


# Gradient Descent

In [21]:
# learning rate -> lr = 0.01
# W := W - alpha * d / dw * cost(w)
optimizer = optim.SGD([W, b], lr = 0.01)

In [23]:
# 옵티마이저 계산
optimizer.zero_grad()
# cost 계산
cost.backward()
# 옵티마이저 갱신
optimizer.step()

In [24]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


check if the hypothesis get better

In [25]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [26]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


In [27]:
# data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# 모델 초기화
W = torch.zeros(1, requires_grad= True)
b = torch.zeros(1, requires_grad= True)

# 옵티마이저 설정
optimizer = optim.SGD([W, b], lr = 0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

  # H(x) 계산
  hypothesis = x_train * W + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 계산
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d} / {} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), b.item(), cost.item()
    ))

Epoch    0 / 1000 W: 0.093, b: 0.040 Cost: 4.666667
Epoch  100 / 1000 W: 0.873, b: 0.289 Cost: 0.012043
Epoch  200 / 1000 W: 0.900, b: 0.227 Cost: 0.007442
Epoch  300 / 1000 W: 0.921, b: 0.179 Cost: 0.004598
Epoch  400 / 1000 W: 0.938, b: 0.140 Cost: 0.002842
Epoch  500 / 1000 W: 0.951, b: 0.110 Cost: 0.001756
Epoch  600 / 1000 W: 0.962, b: 0.087 Cost: 0.001085
Epoch  700 / 1000 W: 0.970, b: 0.068 Cost: 0.000670
Epoch  800 / 1000 W: 0.976, b: 0.054 Cost: 0.000414
Epoch  900 / 1000 W: 0.981, b: 0.042 Cost: 0.000256
Epoch 1000 / 1000 W: 0.985, b: 0.033 Cost: 0.000158
